name: CI/CD pipeline to build and deploy a static website

env:
  AWS_REGION: 'eu-central-1'
  AWS_S3_BUCKET_NAME: 'alpaked-task-s3-bucket'

on:
  # Triggers the workflow on push events but only for the master branch
  push:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'

      - name: Install dependencies
        run: npm ci

      - name: Install AWS CDK Toolkit and Gatsby CLI
        run: npm install -g aws-cdk@1.92.0 gatsby-cli

      - name: Set up a content model and create a configuration file
        run: |
          npm run setup -- \
            --spaceId ${{ secrets.CONTENTFUL_SPACE_ID }} \
            --managementToken ${{ secrets.CONTENTFUL_MANAGEMENT_TOKEN }} \
            --accessToken ${{ secrets.CONTENTFUL_ACCESS_TOKEN }}

      - name: Run a production build into ./public
        run: gatsby build

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Create and provision AWS infrastructure with AWS CDK
        run: |
          cd ./aws-cdk-git-actions
          pip3 install -r requirements.txt
          cdk deploy --require-approval never
          cd -

      - name: Deploy built website to AWS S3 Bucket
        run: |
          aws s3 sync ./public s3://${{ env.AWS_S3_BUCKET_NAME }} \
            --acl public-read

  test:
    needs: build
    runs-on: ubuntu-latest

    steps:

      - name: Check a website availability
        run: |
          curl -Is https://${{ env.AWS_S3_BUCKET_NAME }}.s3.${{ env.AWS_REGION }}.amazonaws.com/index.html | head -n -1
